### ISSUE TITLE
matches data automatically inserted into lovelace raw editor

### ISSUE THREAD

**Issue by lockyt** [postlund/search-card#11]
Hi @postlund.  Thanks for making a great search bar - just what I was looking for.

However, I seem to be having a problem.  I have added the following to the badges section on the lovelace configuration:

```
      - max_results: 10
        type: 'custom:search-card'
```

When I save it, it works just fine, giving me a search bar along the very top of the screen where I can search etc no problems.

However, when I go back into the raw config editor, it has changed it to this:

```
      - max_results: 10
        type: 'custom:search-card'
        actions:
          - &ref_0
            matches: '^((magnet:.*)|(.*.torrent.*))$'
            name: Add to Transmission
            icon: 'mdi:progress-download'
            service: transmission.add_torrent
            service_data:
              torrent: '{1}'
          - *ref_0
```
 and if I save and go back into the editor again, it appends even more of the same each time:

```
      - max_results: 10
        type: 'custom:search-card'
        actions:
          - &ref_0
            matches: '^((magnet:.*)|(.*.torrent.*))$'
            name: Add to Transmission
            icon: 'mdi:progress-download'
            service: transmission.add_torrent
            service_data:
              torrent: '{1}'
          - *ref_0
          - *ref_0
          - matches: '^((magnet:.*)|(.*.torrent.*))$'
            name: Add to Transmission
            icon: 'mdi:progress-download'
            service: transmission.add_torrent
            service_data:
              torrent: '{1}'
```

The appended data doesn't stop it working but it obviously is doing something strange.   Seems like a bug as I don't even have a torrent integration.  Any ideas as to why it keeps doing it?  Perhaps cause it is in the badges section?  I wanted to have it in the badges section to be at the very top and full width of the screen.

Looking forward to hearing from you.

Thanks.
