### ISSUE TITLE
Lovelace card configuration was filled with transmission entries, although i dont have transmission installed

### ISSUE THREAD

**Issue by krasatos** [postlund/search-card#19]
Hey there, and thanks for this wonderful plugin.

Although this created no issue, i stumbled upon it on my raw config editor and thought i should mention it because it's weird, as i have nothing installed relative to transmission, or torrents in general

The card configuration was filled with these entries:
```
actions:
  - icon: 'mdi:progress-download'
    matches: '^((magnet:.*)|(.*.torrent.*))$'
    name: Add to Transmission
    service: transmission.add_torrent
    service_data:
      torrent: '{1}'
```

this is the full configuration:
```
actions:
  - icon: 'mdi:progress-download'
    matches: '^((magnet:.*)|(.*.torrent.*))$'
    name: Add to Transmission
    service: transmission.add_torrent
    service_data:
      torrent: '{1}'
  - icon: 'mdi:progress-download'
    matches: '^((magnet:.*)|(.*.torrent.*))$'
    name: Add to Transmission
    service: transmission.add_torrent
    service_data:
      torrent: '{1}'
....
[repeats for like 100 times]
....
  - icon: 'mdi:progress-download'
    matches: '^((magnet:.*)|(.*.torrent.*))$'
    name: Add to Transmission
    service: transmission.add_torrent
    service_data:
      torrent: '{1}'
max_results: 10
style: |
  ha-card {
    color: var(--button-card-color)
  } 
type: 'custom:search-card'

```

i scrapped all the actions: part and it went back to how it should be. 
```
max_results: 10
style: |
  ha-card {
    color: var(--button-card-color)
  } 
type: 'custom:search-card'

```
I'm mentioning it as i have no idea how they got there.
